extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  otlp_grpc/data_prepper_traces:
    endpoint: data-prepper:21890
    tls:
      insecure: true

  otlp_grpc/data_prepper_logs:
    endpoint: data-prepper:21892
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:8889

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_grpc/data_prepper_traces
    logs:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_grpc/data_prepper_logs
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
